quizmaker/quizmaker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('quizmaker_app/', include('quizmaker_app.urls')),
    path('admin/', admin.site.urls),
]

quizmaker/quizmaker_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('createquiz', views.makeQuiz),
    path('takequiz/<int:quiz_id>/', views.takeQuiz),
    path('viewresults/<int:quiz_id>/', views.viewQuizResults),
    path('viewquiz/<int:quiz_id>/', views.viewMadeQuiz),
    path('takequiz/<int:quiz_id>/go/', views.takingQuiz)
]

quizmaker/quizmaker_app/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Quiz(models.Model):
	quiz_id = models.IntegerField(unique=True);

	#....
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

	#....
	def __str__(self):
		return "Quiz #" + str(self.quiz_id)


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

	#....
	def __str__(self):
		return self.question_text


class Answer(models.Model):
	answer_text = models.CharField(max_length=200)
	is_correct = models.BooleanField()

	question = models.ForeignKey(Question, on_delete=models.CASCADE)

	#....
	def __str__(self):
		tail_str = ""
		if (self.is_correct):
			tail_str = " (correct)"
		return self.answer_text + str(tail_str)

quizmaker/quizmaker_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.template import loader

from .models import Quiz

unviewed_results = False

# Create your views here.

def index(request):
	template = loader.get_template('quizmaker_app/index.html')
	context = {
		'unviewed_results': unviewed_results
	}
	return HttpResponse(template.render(context, request))

def makeQuiz(request):
	return HttpResponse("You want to make a quiz!")

def takeQuiz(request, quiz_id):
	response = "You want to take a quiz you made! Quiz %s"
	try :
		quiz = Quiz.objects.get(pk=quiz_id)
	except Quiz.DoesNotExist:
		raise Http404("Quiz does not exist")

	unviewed_results = True
	context = {'quiz_id' : quiz_id}
	return render(request, 'quizmaker_app/takequiz.html', context)

def takingQuiz(request, quiz_id):
	try :
		quiz = Quiz.objects.get(pk=quiz_id)
	except Quiz.DoesNotExist:
		raise Http404("Internal error....")

	context = {'quiz_id' : quiz_id, 'quiz' : quiz}

	return render(request, 'quizmaker_app/takequiz_go.html', context)


def viewQuizResults(request, quiz_id):
	response = "You want to see your results after taking a quiz! Quiz %s"
	return HttpResponse(response % quiz_id)

def viewMadeQuiz(request, quiz_id):
	response = "You want to view a quiz you made! Quiz %s"
	return HttpResponse(response % quiz_id)

quizmaker/quizmaker_app/templates/quizmaker_app/index.html
<html>
<body>
<h1>
Welcome to the quizmaker app!
</h1>

{% if unviewed_results %}
 <button type="button">View recent results!</button> 
{% endif %}
	
 <button type="button">Make quiz</button> 
 <button type="button">Take quiz</button> 
 <button type="button">View results</button> 
 <button type="button">View created quiz</button> 

</body>
</html>

quizmaker/quizmaker_app/templates/quizmaker_app/takequiz.html
<html>
<body>

<p>
	Quiz number {{ quiz_id }}
</p>

<p>
	Time limit = 10 minutes
</p>

<button>
Start quiz
</button>

</body>

</body>
</html>

quizmaker/quizmaker_app/templates/quizmaker_app/takequiz_go.html
<html>
<body>


<h1> Quiz #{{ quiz_id }} </h1>


{% for question in quiz.question_set.all %}
<h3> {{ question.question_text }} </h3>

<ol type ='A'>
{% for answer in question.answer_set.all %}
<li> {{ answer.answer_text }} </li>
{% endfor %}
</ol>

{% endfor %}


</body>
</html>